#%RAML 1.0
title: Ksquare university training


/requests:
  /component:
    get:
    post:
    
  /rest:
    /{category}:
      uriParameters:
        category: 
          type: string
          enum: [SFO,LAX,CLE,PDX,PDF]
      get:
  /soap:
    get:
        
  
/errors:
  /default:
    get:
  /continue:
    get: 
  /propagate:
    get: 
  /validate:
    get: 
  /combined:
    get:

  
/flows:
  /choice:
    /{path}:
      uriParameters:
        path: 
          type: string
          enum: ['c','s','r']
      get:
  /scattergather:
    get:
  /rouundrobind:
    get:
    
  
 